### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by MaddyGuthridge** [COMP6991UNSW/ircat#2]
It'd be nice if the project had a license so that it could be safely used within other projects given that the terms are followed. MIT would probably be good, as it allows for reuse in private code provided that credit (and copyright info) are given, making it great for assignments.

**Comment by tfpk** [comment]
I'd be worried about adding a license to this, because I explicitly don't have the right to license this out; because it's a direct product of my employment with UNSW.

I'd have to talk with UNSW legal to figure out if I even can license it out... and that's not really worthwhile.
